added summary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,3 +77,24 @@ jobs:
       
       - name: e2e
         run: npm run test:e2e
+  
+  ci-summary:
+    name: ИТОГ
+    runs-on: ubuntu-latest
+    needs: [lint, unit-test, integrations-test, e2e-test]
+    if: always()
+    steps:
+     - name: msg
+       run: |
+        l="${{ needs.lint.result }}"
+        u="${{ needs.unit-test.result }}"
+        i="${{ needs.integrations-test.result }}"
+        e="${{ needs.e2e-test.result }}"
+        echo "lint=$l test-unit=$u test-integration=$i e2e=$e"
+          if [ "$l" = "success" ] && [ "$u" = "success" ] && \
+             [ "$i" = "success" ] && [ "$e" = "success" ]; then
+            echo "::notice title=CI успешно::Все проверки завершены успешно: ESLint, unit-тесты, интеграционные тесты, e2e."
+            exit 0
+          fi
+          echo "::error title=CI не прошёл::Одна или несколько проверок завершились с ошибкой или были отменены."
+          exit 1
